[project]
name = "miniagent-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckduckgo-search>=7.5.5",
    "openai>=1.69.0",
    "requests>=2.32.3",
    "ruff>=0.11.2",
]
